services:
  - type: web
    plan: free
    name: PRIYANKABOT
    env: python
    buildCommand: 
    startCommand: "python3 -m AviaxMusic"
    repo: https://github.com/Jodmarmik/AviaxMusic


    branch: main
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: LOG_GROUP_ID
        sync: false  
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
    autoDeploy: false
